name: CI
on:
  push:
    branches:
      - main
      - next
      - v1.x
  pull_request:
    branches:
      - main
      - next
      - v1.x
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format check
        run: pnpm format:check

      - name: Lint files
        run: pnpm lint:ci

      - name: Typecheck files
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: pnpm test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: pnpm build

      - name: Build example for Web
        run: pnpm example:build

      - name: Typecheck docs
        run: pnpm docs:typecheck

      - name: Build docs
        run: pnpm docs:build
